export const GETOUCH_LOCAL_SOURCE_MODEL = 'Qwen/Qwen3-8B-FP8';
export const GETOUCH_LOCAL_MODEL_DISPLAY_NAME = 'Qwen3 8B FP8';
export const GETOUCH_LOCAL_VLLM_SERVICE_NAME = 'vllm-qwen3-8b-fp8';
export const GETOUCH_LOCAL_VLLM_SERVED_MODEL_NAME = 'getouch-qwen3-8b';
export const GETOUCH_LOCAL_LITELLM_MODEL_ALIAS = 'getouch-qwen3-8b';
export const GETOUCH_LOCAL_STABLE_ALIAS = 'getouch-local-chat';
export const GETOUCH_LOCAL_DEFAULT_ALIAS = GETOUCH_LOCAL_STABLE_ALIAS;
export const GETOUCH_LOCAL_VLLM_INTERNAL_ENDPOINT = `http://${GETOUCH_LOCAL_VLLM_SERVICE_NAME}:8000/v1`;

export const GETOUCH_LOCAL_ALIAS_OPTIONS = [
  GETOUCH_LOCAL_STABLE_ALIAS,
  GETOUCH_LOCAL_LITELLM_MODEL_ALIAS,
] as const;